### ISSUE TITLE
Agressive eslint

### ISSUE THREAD

**Issue by toporan** [tonik/html-frontend-boilerplate#10]
Hi guys
This is a great boilerplate, but the linting is way too agressive. I've spent 10 min. on finding/fixing the 156 eslint "errors".
Is there a quick and easy way to disable it?

Thanks

**Comment by jedrzejchalubek** [comment]
Linting configuration is stored in two files: `.eslintrc` for JavaScript and `.stylelintrc` for Sass. By default they use our internal configs. However, feel free to remove it or swap for less strict config (like stylelint-config-standard).

I would recommend you to browser through ESLint documentation as this is a wide topic.
