### ISSUE TITLE
Rollup can't resolve specific packages

### ISSUE THREAD

**Issue by paweljanuszkiewicz** [tonik/html-frontend-boilerplate#13]
Checked for axios and fetch, possible for other packages

Reproduce error:
npm i axios --save

app.js
```
import axios from 'axios'
console.log(axios)
```

npm run dev

**Comment by jedrzejchalubek** [comment]
Axios needs additional rollup plugins to properly compile axios for the file.

Issue to follow up: https://github.com/axios/axios/issues/1259
