### ISSUE TITLE
Why we support only .ttf in this build task ?

### ISSUE THREAD

**Issue by rybkowskigrzegorz** [tonik/html-frontend-boilerplate#3]
https://github.com/tonik/html-frontend-boilerplate/blob/2340a1bb264893df8d63b36a45b092c85a6e4707/build/tasks/font/build.js#L7

**Comment by jedrzejchalubek** [comment]
The `gulp-fontmin` is a wrapper around `fontmin` which is basically a web font converter. It turns TTF files into SVG, EOT, WOFF.

This task help building web fonts from standard desktop font files. Dunno why it is named fontmin ¯\_(ツ)_/¯

**Comment by rybkowskigrzegorz** [comment]
Ok, but what with the .scss/.css file. Should i point font src to .svg/.eot/.woff files even that they are not included inside of assets folder? 

I know it makes things easier at all, but do we have 100% sure how this task is working? For example, what is it doing with fonts protected by a certificate or can it handle big font files (like with Chinese characters)? I'm aiming for whether we actually need this task as a default one?

**Comment by jedrzejchalubek** [comment]
> Ok, but what with the .scss/.css file. Should i point font src to .svg/.eot/.woff files even that they are not included inside of assets folder?

Yes, font files lands in `public/fonts` directory and all references from CSS files should point to that folder.

> I know it makes things easier at all, but do we have 100% sure how this task is working? For example, what is it doing with fonts protected by a certificate or can it handle big font files (like with Chinese characters)?

Until now, I did not have problems with it.

> I'm aiming for whether we actually need this task as a default one?

That's the question, more opinions are needed here :) It was supposed to make things easier, so you don't have to use font convert services and manually copying it over into `public` directory. On the other hand, it's only a boilerplate and should be adjusted to the final project.

**Comment by jedrzejchalubek** [comment]
Fixed with https://github.com/tonik/html-frontend-boilerplate/commit/6afe1e018d3b5106194a0cd3377c01831473711d
