### ISSUE TITLE
Separate SVG

### ISSUE THREAD

**Issue by rybkowskigrzegorz** [tonik/html-frontend-boilerplate#4]
I recommend making separated task and folder for ico (.svg). For now, it's a bit confusing that we need to keep both .png and .svg icons like arrow/socials icons etc. in the same directory.

**Comment by rybkowskigrzegorz** [comment]
```const isdev = require('isdev')

const gulp = require('gulp')
const gulpif = require('gulp-if')
const svgmin = require('gulp-svgmin')

const message = require('../../lib/message')

module.exports = () => {
  return gulp
    .src('src/ico/**/*.svg')
    .pipe(gulpif(!isdev,
      svgmin({
        js2svg: {
          pretty: true
        }
      })
    ))
    .on('error', message.error('SVG: Minification'))
    .pipe(gulp.dest('../public/ico'))
}
```

task example

**Comment by jedrzejchalubek** [comment]
Current task for images uses `imagemin` which can optimize SVG files too. You only have to create files in `/images` dir eg. `images/icons`. 

Creating new task only for `svg` will have any additional benefits?

**Comment by rybkowskigrzegorz** [comment]
Overall it's a matter of taste, but I would prefer to keep my .svg (ico folder) outside images folder. But if i'm in a minority - let's keep it that way

**Comment by jedrzejchalubek** [comment]
We will keep it as it is.
